### ISSUE TITLE
Upgrade DMN editor and support more current version of the DMN spec

### ISSUE THREAD

**Issue by blakeroyer** [materna-se/declab#82]
First of all, thank you for making such a helpful tool available. We have found it to be the most featured and stable environment available for collaborating and testing DMN models.

We are wondering if there are any plans to update the DMN editor, as there have been many improvements made to the library, including features like copy-paste, more robust row and column insertion, etc. (summary here https://github.com/kiegroup/kie-tools/pull/1562)

As well, are there any plans to support more recent DMN specs? There are some new FEEL functions, such as `round up` that are not supported in the declab tool, which came with DMN 1.4 that is supported in recent versions of Drools.

Thank you in advance.

**Comment by oas** [comment]
Thank you very much for reaching out and for your feedback. We are pleased to hear that you find it useful!

We are currently working hard on declab 3.0, which will encompass a multitude of improvements and new functionalities. That being said, we are currently planning to release a patch to declab 2.10, to address the topics you highlighted among some bug fixes.

I will keep the issue open and will reach out again once the updated version is published. In the meantime, as we are actively working on the new version, should you have any further suggestions or wishes, please do not hesitate to share them either using GitHub issues by contacting me at jonas.tamimi [at] materna.de!

**Comment by oas** [comment]
Hello, we have released the updated version of declab yesterday, which includes the mentioned changes and several bugfixes :)
